# Generated by Django 3.1.1 on 2020-09-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_titulo', models.CharField(max_length=200)),
                ('serie_temporadas', models.IntegerField(default=1)),
                ('serie_genero', models.CharField(max_length=50)),
            ],
        ),
    ]
