# Generated by Django 3.1.1 on 2020-09-30 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_episodio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_titulo', models.CharField(max_length=200)),
                ('review_texto', models.TextField()),
                ('review_avaliacao', models.FloatField()),
                ('review_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.serie')),
            ],
        ),
    ]
