# Generated by Django 3.1.1 on 2020-10-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtor_nome', models.CharField(max_length=200)),
                ('produtor_series', models.ManyToManyField(to='quickstart.Serie')),
            ],
        ),
    ]
